# This workflow run similarly to `automatic-build.yml` workflow
# but it does not publish the resulting page and instead only report build errors.
# this is useful for when handling pull request.
name: Pull-request Check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Building mdbook
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup mdbook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: '0.4.7'
        
    - name: Build website
      run: mdbook build
